/*****************************
CSharpWriter is a RTF style Text writer control written by C#,Currently,
it use <LGPL> license.More than RichTextBox, 
It is provide a DOM to access every thing in document and save in XML format.
It can use in WinForm.NET ,WPF,Console application.Any idea about CSharpWriter 
can write to 28348092@qq.com(or yyf9989@hotmail.com). 
Project web site is [https://github.com/dcsoft-yyf/CSharpWriter].
*****************************///@DCHC@
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSoft.Script {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSoft.Script.ScriptStrings", typeof(ScriptStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分析出VB脚本方法“{0}”。 的本地化字符串。
        /// </summary>
        internal static string AnalyseVBMethod_Name {
            get {
                return ResourceManager.GetString("AnalyseVBMethod_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .NET程序集文件(*.exe,*.dll)|*.dll;*.exe 的本地化字符串。
        /// </summary>
        internal static string AssemblyFileFilter {
            get {
                return ResourceManager.GetString("AssemblyFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空VB脚本引擎。 的本地化字符串。
        /// </summary>
        internal static string ClearVBAEngine {
            get {
                return ResourceManager.GetString("ClearVBAEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭VB脚本引擎。 的本地化字符串。
        /// </summary>
        internal static string CloseVBAEngine {
            get {
                return ResourceManager.GetString("CloseVBAEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编译错误“{0}”。 的本地化字符串。
        /// </summary>
        internal static string CompileError_Message {
            get {
                return ResourceManager.GetString("CompileError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态编译结果 的本地化字符串。
        /// </summary>
        internal static string DymamicCompilerResult {
            get {
                return ResourceManager.GetString("DymamicCompilerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的“{0}”语言 的本地化字符串。
        /// </summary>
        internal static string NotSupportLanguage_Language {
            get {
                return ResourceManager.GetString("NotSupportLanguage_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用 的本地化字符串。
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回类型 的本地化字符串。
        /// </summary>
        internal static string ReturnType {
            get {
                return ResourceManager.GetString("ReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始动态编译 的本地化字符串。
        /// </summary>
        internal static string StartDynamicCompile {
            get {
                return ResourceManager.GetString("StartDynamicCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用{0}个程序集，包含{1}个名称空间。 的本地化字符串。
        /// </summary>
        internal static string VBAOptionString_RefCount_NSCount {
            get {
                return ResourceManager.GetString("VBAOptionString_RefCount_NSCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行VB脚本方法“{0}”时发生错误“{1}”！ 的本地化字符串。
        /// </summary>
        internal static string VBARuntimeError_Method_Message {
            get {
                return ResourceManager.GetString("VBARuntimeError_Method_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Warring {
            get {
                return ResourceManager.GetString("Warring", resourceCulture);
            }
        }
    }
}
