/*****************************
CSharpWriter is a RTF style Text writer control written by C#,Currently,
it use <LGPL> license.More than RichTextBox, 
It is provide a DOM to access every thing in document and save in XML format.
It can use in WinForm.NET ,WPF,Console application.Any idea about CSharpWriter 
can write to 28348092@qq.com(or yyf9989@hotmail.com). 
Project web site is [https://github.com/dcsoft-yyf/CSharpWriter].
*****************************///@DCHC@
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSoft.Common {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValueValidateStyleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValueValidateStyleStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSoft.Common.ValueValidateStyleStrings", typeof(ValueValidateStyleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 文本不包含在列表“{0}”。 的本地化字符串。
        /// </summary>
        public static string ExcludeRange_Range {
            get {
                return ResourceManager.GetString("ExcludeRange_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据不能为空。 的本地化字符串。
        /// </summary>
        public static string ForbidEmpty {
            get {
                return ResourceManager.GetString("ForbidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本过短，不得少于 {0} 个字符。 的本地化字符串。
        /// </summary>
        public static string LessThanMinLength_Length {
            get {
                return ResourceManager.GetString("LessThanMinLength_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于最小值 {0}。 的本地化字符串。
        /// </summary>
        public static string LessThanMinValue_Value {
            get {
                return ResourceManager.GetString("LessThanMinValue_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本过长，不得超过 {0} 个字符。 的本地化字符串。
        /// </summary>
        public static string MoreThanMaxLength_Length {
            get {
                return ResourceManager.GetString("MoreThanMaxLength_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过最大值 {0}。 的本地化字符串。
        /// </summary>
        public static string MoreThanMaxValue_Value {
            get {
                return ResourceManager.GetString("MoreThanMaxValue_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须为日期时间格式。 的本地化字符串。
        /// </summary>
        public static string MustDateTimeType {
            get {
                return ResourceManager.GetString("MustDateTimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须为日期格式。 的本地化字符串。
        /// </summary>
        public static string MustDateType {
            get {
                return ResourceManager.GetString("MustDateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须为整数。 的本地化字符串。
        /// </summary>
        public static string MustInteger {
            get {
                return ResourceManager.GetString("MustInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须为数值。 的本地化字符串。
        /// </summary>
        public static string MustNumeric {
            get {
                return ResourceManager.GetString("MustNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须为时间格式。 的本地化字符串。
        /// </summary>
        public static string MustTimeType {
            get {
                return ResourceManager.GetString("MustTimeType", resourceCulture);
            }
        }
    }
}
