/*****************************
CSharpWriter is a RTF style Text writer control written by C#,Currently,
it use <LGPL> license.More than RichTextBox, 
It is provide a DOM to access every thing in document and save in XML format.
It can use in WinForm.NET ,WPF,Console application.Any idea about CSharpWriter 
can write to 28348092@qq.com(or yyf9989@hotmail.com). 
Project web site is [https://github.com/dcsoft-yyf/CSharpWriter].
*****************************///@DCHC@
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSoft.DataSourceDom {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataSourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataSourceStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSoft.DataSourceDom.DataSourceStrings", typeof(DataSourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误“{0}”。 的本地化字符串。
        /// </summary>
        internal static string AlertError_Message {
            get {
                return ResourceManager.GetString("AlertError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入命令文本！ 的本地化字符串。
        /// </summary>
        internal static string AlertInputCommandText {
            get {
                return ResourceManager.GetString("AlertInputCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”要求的数据类型为“{1}”，其值“{2}”格式不对。 的本地化字符串。
        /// </summary>
        internal static string BadParameterValueType_Name_Type_Value {
            get {
                return ResourceManager.GetString("BadParameterValueType_Name_Type_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭数据库连接“{0}”。 的本地化字符串。
        /// </summary>
        internal static string CloseConnection_String {
            get {
                return ResourceManager.GetString("CloseConnection_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”按照“{1}”分组，按照“{2}”交叉。 的本地化字符串。
        /// </summary>
        internal static string DataSourceCrossData_Name_Groups_Crosses {
            get {
                return ResourceManager.GetString("DataSourceCrossData_Name_Groups_Crosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”按照“{1}”分组。 的本地化字符串。
        /// </summary>
        internal static string DataSourceGroup_Name_Group {
            get {
                return ResourceManager.GetString("DataSourceGroup_Name_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”使用数据库连接“{1}”执行SQL查询“{2}”。 的本地化字符串。
        /// </summary>
        internal static string ExecuteSQL_Name_Connection_SQL {
            get {
                return ResourceManager.GetString("ExecuteSQL_Name_Connection_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”使用条件“{1}”过滤获得“{2}”条记录。 的本地化字符串。
        /// </summary>
        internal static string FilterDataRow_DataNode_Expression_Result {
            get {
                return ResourceManager.GetString("FilterDataRow_DataNode_Expression_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes,No|True,False|是,否|真,假|好,差|男,女|是,|,否 的本地化字符串。
        /// </summary>
        internal static string FormatSample_Boolean {
            get {
                return ResourceManager.GetString("FormatSample_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 00.00|大写中文|小写中文|#.00|c 的本地化字符串。
        /// </summary>
        internal static string FormatSample_Currency {
            get {
                return ResourceManager.GetString("FormatSample_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-MM-dd HH:mm:ss|yyyy-MM-dd|yyyy-MM-dd hh:mm:ss|HH:mm:ss|yyyy年MM月dd日|yyyy年MM月dd日 HH时mm分ss秒|d|D|f|F 的本地化字符串。
        /// </summary>
        internal static string FormatSample_DateTime {
            get {
                return ResourceManager.GetString("FormatSample_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “{0}”不是合法的数据源名称,不得以数字开头,不得包含非文字字符。 的本地化字符串。
        /// </summary>
        internal static string InvalidateName_Name {
            get {
                return ResourceManager.GetString("InvalidateName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”名称不合适。 的本地化字符串。
        /// </summary>
        internal static string InvalidateNodeName_Path {
            get {
                return ResourceManager.GetString("InvalidateNodeName_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”需要绑定字段。 的本地化字符串。
        /// </summary>
        internal static string InvalidateRequireFieldName_Path {
            get {
                return ResourceManager.GetString("InvalidateRequireFieldName_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取数据完毕。 的本地化字符串。
        /// </summary>
        internal static string LoadDataComplete {
            get {
                return ResourceManager.GetString("LoadDataComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从文件“{0}”加载数据集XML文档时发生错误“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadDataSetXMLError_File_Message {
            get {
                return ResourceManager.GetString("LoadDataSetXMLError_File_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载CSV文件“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadingCSV_Name_URL {
            get {
                return ResourceManager.GetString("LoadingCSV_Name_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载CSV文本“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadingCSVText_Name_Length {
            get {
                return ResourceManager.GetString("LoadingCSVText_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载内置数据表“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadingDataTable_Name_Name {
            get {
                return ResourceManager.GetString("LoadingDataTable_Name_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载DBF数据文件“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadingDBaseIII_Name_URL {
            get {
                return ResourceManager.GetString("LoadingDBaseIII_Name_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载EXCEL文件“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadingExcelFile_Name_URL {
            get {
                return ResourceManager.GetString("LoadingExcelFile_Name_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”查询文件目录“{1}”的信息。 的本地化字符串。
        /// </summary>
        internal static string LoadingFileSystem_Name_Path {
            get {
                return ResourceManager.GetString("LoadingFileSystem_Name_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载HTML文件“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadingHTML_Name_URL {
            get {
                return ResourceManager.GetString("LoadingHTML_Name_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载XML节点“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadingXML_Name_Node {
            get {
                return ResourceManager.GetString("LoadingXML_Name_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载字符长度为“{2}”的XML文本“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadingXML_Name_Text_Length {
            get {
                return ResourceManager.GetString("LoadingXML_Name_Text_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载字符长度为“{1}”的XML文本。 的本地化字符串。
        /// </summary>
        internal static string LoadingXML_Name_TextLength {
            get {
                return ResourceManager.GetString("LoadingXML_Name_TextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”正在加载XML文件“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadingXML_Name_URL {
            get {
                return ResourceManager.GetString("LoadingXML_Name_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载XML文档“{0}”。 的本地化字符串。
        /// </summary>
        internal static string LoadXML_Key {
            get {
                return ResourceManager.GetString("LoadXML_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载XML文本“{0}”。 的本地化字符串。
        /// </summary>
        internal static string LoadXML_Text {
            get {
                return ResourceManager.GetString("LoadXML_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载XML文档“{0}”时发生错误“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadXMLError_Key_Message {
            get {
                return ResourceManager.GetString("LoadXMLError_Key_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载XML文档时发生错误“{0}”。 的本地化字符串。
        /// </summary>
        internal static string LoadXMLError_Message {
            get {
                return ResourceManager.GetString("LoadXMLError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”处于分组时必须指定Crosses值。 的本地化字符串。
        /// </summary>
        internal static string MustSpecifyGroupWhenCross_Name {
            get {
                return ResourceManager.GetString("MustSpecifyGroupWhenCross_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有任何数据。 的本地化字符串。
        /// </summary>
        internal static string NoneData {
            get {
                return ResourceManager.GetString("NoneData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”查询数据时发生错误“{1}”。 的本地化字符串。
        /// </summary>
        internal static string QueryError_Name_Message {
            get {
                return ResourceManager.GetString("QueryError_Name_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有为节点“{0}”查到任何数据！ 的本地化字符串。
        /// </summary>
        internal static string QueryNothing_Name {
            get {
                return ResourceManager.GetString("QueryNothing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”读取类型为“{1}”的系统日志数据。 的本地化字符串。
        /// </summary>
        internal static string ReadEventLog_Name_Style {
            get {
                return ResourceManager.GetString("ReadEventLog_Name_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”使用“{1}”查询WMI数据。 的本地化字符串。
        /// </summary>
        internal static string ReadWMI_Name_Query {
            get {
                return ResourceManager.GetString("ReadWMI_Name_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   中文ABC   的本地化字符串。
        /// </summary>
        internal static string SampleText {
            get {
                return ResourceManager.GetString("SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存数据集XML文件到“{0}”时发生错误“{1}”。 的本地化字符串。
        /// </summary>
        internal static string SaveDataSetXMLError_File_Message {
            get {
                return ResourceManager.GetString("SaveDataSetXMLError_File_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置当前目录为“{0}”。 的本地化字符串。
        /// </summary>
        internal static string SetCurrentDirectory_Directory {
            get {
                return ResourceManager.GetString("SetCurrentDirectory_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点“{0}”使用SQL参数：{1} 的本地化字符串。
        /// </summary>
        internal static string SQLParameter_Name_Value {
            get {
                return ResourceManager.GetString("SQLParameter_Name_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统提示 的本地化字符串。
        /// </summary>
        internal static string SystemAlert {
            get {
                return ResourceManager.GetString("SystemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共{0}行{1}列 的本地化字符串。
        /// </summary>
        internal static string Total_Rows_Cols {
            get {
                return ResourceManager.GetString("Total_Rows_Cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源节点“{0}”更新数据时发生错误“{1}”。 的本地化字符串。
        /// </summary>
        internal static string UpdateError_Name_Message {
            get {
                return ResourceManager.GetString("UpdateError_Name_Message", resourceCulture);
            }
        }
    }
}
