/*****************************
CSharpWriter is a RTF style Text writer control written by C#,Currently,
it use <LGPL> license.More than RichTextBox, 
It is provide a DOM to access every thing in document and save in XML format.
It can use in WinForm.NET ,WPF,Console application.Any idea about CSharpWriter 
can write to 28348092@qq.com(or yyf9989@hotmail.com). 
Project web site is [https://github.com/dcsoft-yyf/CSharpWriter].
*****************************///@DCHC@
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSoft.Barcode {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BarcodeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BarcodeStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSoft.Barcode.BarcodeStrings", typeof(BarcodeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Codabar条码长度不得小于3，而且开头和结尾是字符&apos;A&apos;或&apos;B&apos;或&apos;C&apos;或&apos;D&apos;。 的本地化字符串。
        /// </summary>
        internal static string CodabarError {
            get {
                return ResourceManager.GetString("CodabarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code11条码只能包含数字和字符&apos;-&apos;。 的本地化字符串。
        /// </summary>
        internal static string Code11Error {
            get {
                return ResourceManager.GetString("Code11Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为Code128条码判别起始字符。 的本地化字符串。
        /// </summary>
        internal static string Code128CannotDetermineStart {
            get {
                return ResourceManager.GetString("Code128CannotDetermineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为Code128条码插入“{0}” 的本地化字符串。
        /// </summary>
        internal static string Code128CannotFind_Value {
            get {
                return ResourceManager.GetString("Code128CannotFind_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为Code128条码插入字符错误： 的本地化字符串。
        /// </summary>
        internal static string Code128InsertError {
            get {
                return ResourceManager.GetString("Code128InsertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code128:错误的数据或格式. 的本地化字符串。
        /// </summary>
        internal static string Code128InvaliData {
            get {
                return ResourceManager.GetString("Code128InvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code128条码中出现错误的字符“{0}”。 的本地化字符串。
        /// </summary>
        internal static string Code128InvalidateCharacter_Value {
            get {
                return ResourceManager.GetString("Code128InvalidateCharacter_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定格式的Code128条码文本头错误。 的本地化字符串。
        /// </summary>
        internal static string Code128UnknowStart {
            get {
                return ResourceManager.GetString("Code128UnknowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code39条码数据错误（可尝试Code39Extended条码）。 的本地化字符串。
        /// </summary>
        internal static string Code39InvaliData {
            get {
                return ResourceManager.GetString("Code39InvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code93:错误的数据,包含不支持的字符. 的本地化字符串。
        /// </summary>
        internal static string Code93InvaliData {
            get {
                return ResourceManager.GetString("Code93InvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EAN13:错误的国家代码。 的本地化字符串。
        /// </summary>
        internal static string EAN13InvaliCountry {
            get {
                return ResourceManager.GetString("EAN13InvaliCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EAN13条码只能包含12或13个数字字符。 的本地化字符串。
        /// </summary>
        internal static string EAN13InvaliData {
            get {
                return ResourceManager.GetString("EAN13InvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EAN8:错误的数据，只能包含7或8个数字字符。 的本地化字符串。
        /// </summary>
        internal static string EAN8InvaliData {
            get {
                return ResourceManager.GetString("EAN8InvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I25:错误的数据，必须为偶数个数字字符。 的本地化字符串。
        /// </summary>
        internal static string I25InvaliData {
            get {
                return ResourceManager.GetString("I25InvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的条码样式. 的本地化字符串。
        /// </summary>
        internal static string InvaliBarcodeStyle {
            get {
                return ResourceManager.GetString("InvaliBarcodeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISBN:错误的数据，必须为9，10，12或13个数字，可能需要以“978”开头。 的本地化字符串。
        /// </summary>
        internal static string ISBNInvaliData {
            get {
                return ResourceManager.GetString("ISBNInvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JAN13:必须为数字，而且要“49”开头。 的本地化字符串。
        /// </summary>
        internal static string JAN13InvaliData {
            get {
                return ResourceManager.GetString("JAN13InvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSI:必须全部为数字字符。 的本地化字符串。
        /// </summary>
        internal static string MSIInvaliData {
            get {
                return ResourceManager.GetString("MSIInvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Postnet条码文本必须是长度为5、6、9或11的数字。 的本地化字符串。
        /// </summary>
        internal static string PostnetError {
            get {
                return ResourceManager.GetString("PostnetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S25:必须全部为数字字符。 的本地化字符串。
        /// </summary>
        internal static string S25InvaliData {
            get {
                return ResourceManager.GetString("S25InvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码文本不得为空. 的本地化字符串。
        /// </summary>
        internal static string TextMustNotNull {
            get {
                return ResourceManager.GetString("TextMustNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的条码类型 的本地化字符串。
        /// </summary>
        internal static string UnsupportedStyle {
            get {
                return ResourceManager.GetString("UnsupportedStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPCA:错误的国家代码。 的本地化字符串。
        /// </summary>
        internal static string UPCAInvaliCountry {
            get {
                return ResourceManager.GetString("UPCAInvaliCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPCA:必须为12个数字字符。 的本地化字符串。
        /// </summary>
        internal static string UPCAInvaliData {
            get {
                return ResourceManager.GetString("UPCAInvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPCE:必须为8或12个数字字符,可能需要以0或1开头。 的本地化字符串。
        /// </summary>
        internal static string UPCEInvaliData {
            get {
                return ResourceManager.GetString("UPCEInvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPCS2:必须为2个数字。 的本地化字符串。
        /// </summary>
        internal static string UPCS2InvaliData {
            get {
                return ResourceManager.GetString("UPCS2InvaliData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPCS5:必须为5个数字。 的本地化字符串。
        /// </summary>
        internal static string UPCS5InvaliData {
            get {
                return ResourceManager.GetString("UPCS5InvaliData", resourceCulture);
            }
        }
    }
}
