/*****************************
CSharpWriter is a RTF style Text writer control written by C#2.0,Currently,
it use <LGPL> license(maybe change later).More than RichTextBox, 
It is provide a DOM to access every thing in document and save in XML format.
It can use in WinForm.NET ,WPF,Console application.Any idea about CSharpWriter 
can send to 28348092@qq.com(or yyf9989@hotmail.com).
*****************************///@DCHC@
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSoft.CSharpWriter {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WriterStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WriterStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSoft.CSharpWriter.WriterStrings", typeof(WriterStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter&quot;{0}&quot; value type error,type&quot;{1}&quot;,value&quot;{2}&quot;. 的本地化字符串。
        /// </summary>
        internal static string BadParameterValueType_Name_Type_Value {
            get {
                return ResourceManager.GetString("BadParameterValueType_Name_Type_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell 的本地化字符串。
        /// </summary>
        internal static string BorderApplyRangeCell {
            get {
                return ResourceManager.GetString("BorderApplyRangeCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paragraph 的本地化字符串。
        /// </summary>
        internal static string BorderApplyRangeParagraph {
            get {
                return ResourceManager.GetString("BorderApplyRangeParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table 的本地化字符串。
        /// </summary>
        internal static string BorderApplyRangeTable {
            get {
                return ResourceManager.GetString("BorderApplyRangeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string BorderApplyRangeText {
            get {
                return ResourceManager.GetString("BorderApplyRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not search specify content. 的本地化字符串。
        /// </summary>
        internal static string CannotSearchSpecifyContent {
            get {
                return ResourceManager.GetString("CannotSearchSpecifyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于... 的本地化字符串。
        /// </summary>
        internal static string Command_AboutControl {
            get {
                return ResourceManager.GetString("Command_AboutControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员模式 的本地化字符串。
        /// </summary>
        internal static string Command_AdministratorViewMode {
            get {
                return ResourceManager.GetString("Command_AdministratorViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Command_AlignBottomCenter {
            get {
                return ResourceManager.GetString("Command_AlignBottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中对齐 的本地化字符串。
        /// </summary>
        internal static string Command_AlignCenter {
            get {
                return ResourceManager.GetString("Command_AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两边对齐 的本地化字符串。
        /// </summary>
        internal static string Command_AlignJustify {
            get {
                return ResourceManager.GetString("Command_AlignJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左对齐 的本地化字符串。
        /// </summary>
        internal static string Command_AlignLeft {
            get {
                return ResourceManager.GetString("Command_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右对齐 的本地化字符串。
        /// </summary>
        internal static string Command_AlignRight {
            get {
                return ResourceManager.GetString("Command_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色 的本地化字符串。
        /// </summary>
        internal static string Command_BackColor {
            get {
                return ResourceManager.GetString("Command_BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退格 的本地化字符串。
        /// </summary>
        internal static string Command_Backspace {
            get {
                return ResourceManager.GetString("Command_Backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粗体 的本地化字符串。
        /// </summary>
        internal static string Command_Bold {
            get {
                return ResourceManager.GetString("Command_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框和背景样式 的本地化字符串。
        /// </summary>
        internal static string Command_BorderBackgroudFormat {
            get {
                return ResourceManager.GetString("Command_BorderBackgroudFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆点式列表 的本地化字符串。
        /// </summary>
        internal static string Command_BulletedList {
            get {
                return ResourceManager.GetString("Command_BulletedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整洁视图模式 的本地化字符串。
        /// </summary>
        internal static string Command_CleanViewMode {
            get {
                return ResourceManager.GetString("Command_CleanViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交历史痕迹 的本地化字符串。
        /// </summary>
        internal static string Command_ClearUserTrace {
            get {
                return ResourceManager.GetString("Command_ClearUserTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本颜色 的本地化字符串。
        /// </summary>
        internal static string Command_Color {
            get {
                return ResourceManager.GetString("Command_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复杂视图模式 的本地化字符串。
        /// </summary>
        internal static string Command_ComplexViewMode {
            get {
                return ResourceManager.GetString("Command_ComplexViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入域转换为文档内容 的本地化字符串。
        /// </summary>
        internal static string Command_ConvertFieldToContent {
            get {
                return ResourceManager.GetString("Command_ConvertFieldToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档内容转换为输入域 的本地化字符串。
        /// </summary>
        internal static string Command_ConvertToField {
            get {
                return ResourceManager.GetString("Command_ConvertToField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Command_Copy {
            get {
                return ResourceManager.GetString("Command_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向下滚动视图 的本地化字符串。
        /// </summary>
        internal static string Command_CtlMoveDown {
            get {
                return ResourceManager.GetString("Command_CtlMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向上滚动视图 的本地化字符串。
        /// </summary>
        internal static string Command_CtlMoveUp {
            get {
                return ResourceManager.GetString("Command_CtlMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切 的本地化字符串。
        /// </summary>
        internal static string Command_Cut {
            get {
                return ResourceManager.GetString("Command_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试模式 的本地化字符串。
        /// </summary>
        internal static string Command_DebugMode {
            get {
                return ResourceManager.GetString("Command_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示调试输出窗体 的本地化字符串。
        /// </summary>
        internal static string Command_DebugOutputWindow {
            get {
                return ResourceManager.GetString("Command_DebugOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Command_Delete {
            get {
                return ResourceManager.GetString("Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除域 的本地化字符串。
        /// </summary>
        internal static string Command_DeleteField {
            get {
                return ResourceManager.GetString("Command_DeleteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设计模式 的本地化字符串。
        /// </summary>
        internal static string Command_DesignMode {
            get {
                return ResourceManager.GetString("Command_DesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文档默认字体 的本地化字符串。
        /// </summary>
        internal static string Command_DocumentDefaultFont {
            get {
                return ResourceManager.GetString("Command_DocumentDefaultFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档选项... 的本地化字符串。
        /// </summary>
        internal static string Command_DocumentOptions {
            get {
                return ResourceManager.GetString("Command_DocumentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档数据校验 的本地化字符串。
        /// </summary>
        internal static string Command_DocumentValueValidate {
            get {
                return ResourceManager.GetString("Command_DocumentValueValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑文档元素值 的本地化字符串。
        /// </summary>
        internal static string Command_EditElementValue {
            get {
                return ResourceManager.GetString("Command_EditElementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑图像标注 的本地化字符串。
        /// </summary>
        internal static string Command_EditImageAdditionShape {
            get {
                return ResourceManager.GetString("Command_EditImageAdditionShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑VBA脚本 的本地化字符串。
        /// </summary>
        internal static string Command_EditVBAScript {
            get {
                return ResourceManager.GetString("Command_EditVBAScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑文档元素属性 的本地化字符串。
        /// </summary>
        internal static string Command_ElementProperties {
            get {
                return ResourceManager.GetString("Command_ElementProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置域固定宽度 的本地化字符串。
        /// </summary>
        internal static string Command_FieldSpecifyWidth {
            get {
                return ResourceManager.GetString("Command_FieldSpecifyWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整洁打印... 的本地化字符串。
        /// </summary>
        internal static string Command_FileCleanPrint {
            get {
                return ResourceManager.GetString("Command_FileCleanPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件... 的本地化字符串。
        /// </summary>
        internal static string Command_FileNew {
            get {
                return ResourceManager.GetString("Command_FileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件... 的本地化字符串。
        /// </summary>
        internal static string Command_FileOpen {
            get {
                return ResourceManager.GetString("Command_FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面设置... 的本地化字符串。
        /// </summary>
        internal static string Command_FilePageSettings {
            get {
                return ResourceManager.GetString("Command_FilePageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印... 的本地化字符串。
        /// </summary>
        internal static string Command_FilePrint {
            get {
                return ResourceManager.GetString("Command_FilePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印当前页 的本地化字符串。
        /// </summary>
        internal static string Command_FilePrintCurrentPage {
            get {
                return ResourceManager.GetString("Command_FilePrintCurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件 的本地化字符串。
        /// </summary>
        internal static string Command_FileSave {
            get {
                return ResourceManager.GetString("Command_FileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为... 的本地化字符串。
        /// </summary>
        internal static string Command_FileSaveAs {
            get {
                return ResourceManager.GetString("Command_FileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 段落首行缩进 的本地化字符串。
        /// </summary>
        internal static string Command_FirstLineIndent {
            get {
                return ResourceManager.GetString("Command_FirstLineIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        internal static string Command_Font {
            get {
                return ResourceManager.GetString("Command_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体名称 的本地化字符串。
        /// </summary>
        internal static string Command_FontName {
            get {
                return ResourceManager.GetString("Command_FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        internal static string Command_FontSize {
            get {
                return ResourceManager.GetString("Command_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单视图模式 的本地化字符串。
        /// </summary>
        internal static string Command_FormViewMode {
            get {
                return ResourceManager.GetString("Command_FormViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入条码 的本地化字符串。
        /// </summary>
        internal static string Command_InsertBarcode {
            get {
                return ResourceManager.GetString("Command_InsertBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入复选框 的本地化字符串。
        /// </summary>
        internal static string Command_InsertCheckBox {
            get {
                return ResourceManager.GetString("Command_InsertCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入复选框组 的本地化字符串。
        /// </summary>
        internal static string Command_InsertCheckBoxList {
            get {
                return ResourceManager.GetString("Command_InsertCheckBoxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入文档内容链接... 的本地化字符串。
        /// </summary>
        internal static string Command_InsertContentLink {
            get {
                return ResourceManager.GetString("Command_InsertContentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入文档内容... 的本地化字符串。
        /// </summary>
        internal static string Command_InsertFileContent {
            get {
                return ResourceManager.GetString("Command_InsertFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入HTML文档 的本地化字符串。
        /// </summary>
        internal static string Command_InsertHtml {
            get {
                return ResourceManager.GetString("Command_InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入图片 的本地化字符串。
        /// </summary>
        internal static string Command_InsertImage {
            get {
                return ResourceManager.GetString("Command_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入输入域 的本地化字符串。
        /// </summary>
        internal static string Command_InsertInputField {
            get {
                return ResourceManager.GetString("Command_InsertInputField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入软回车 的本地化字符串。
        /// </summary>
        internal static string Command_InsertLineBreak {
            get {
                return ResourceManager.GetString("Command_InsertLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入模式 的本地化字符串。
        /// </summary>
        internal static string Command_InsertMode {
            get {
                return ResourceManager.GetString("Command_InsertMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入页码 的本地化字符串。
        /// </summary>
        internal static string Command_InsertPageInfo {
            get {
                return ResourceManager.GetString("Command_InsertPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入RTF文档 的本地化字符串。
        /// </summary>
        internal static string Command_InsertRTF {
            get {
                return ResourceManager.GetString("Command_InsertRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入纯文本 的本地化字符串。
        /// </summary>
        internal static string Command_InsertString {
            get {
                return ResourceManager.GetString("Command_InsertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入XML文档 的本地化字符串。
        /// </summary>
        internal static string Command_InsertXML {
            get {
                return ResourceManager.GetString("Command_InsertXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        internal static string Command_Italic {
            get {
                return ResourceManager.GetString("Command_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 续打模式 的本地化字符串。
        /// </summary>
        internal static string Command_JumpPrintMode {
            get {
                return ResourceManager.GetString("Command_JumpPrintMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载知识库... 的本地化字符串。
        /// </summary>
        internal static string Command_LoadKBLibrary {
            get {
                return ResourceManager.GetString("Command_LoadKBLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向下移动一行 的本地化字符串。
        /// </summary>
        internal static string Command_MoveDown {
            get {
                return ResourceManager.GetString("Command_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到行尾 的本地化字符串。
        /// </summary>
        internal static string Command_MoveEnd {
            get {
                return ResourceManager.GetString("Command_MoveEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到行首 的本地化字符串。
        /// </summary>
        internal static string Command_MoveHome {
            get {
                return ResourceManager.GetString("Command_MoveHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向左移动 的本地化字符串。
        /// </summary>
        internal static string Command_MoveLeft {
            get {
                return ResourceManager.GetString("Command_MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向下翻页 的本地化字符串。
        /// </summary>
        internal static string Command_MovePageDown {
            get {
                return ResourceManager.GetString("Command_MovePageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向上翻页 的本地化字符串。
        /// </summary>
        internal static string Command_MovePageUp {
            get {
                return ResourceManager.GetString("Command_MovePageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向右移动 的本地化字符串。
        /// </summary>
        internal static string Command_MoveRight {
            get {
                return ResourceManager.GetString("Command_MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到... 的本地化字符串。
        /// </summary>
        internal static string Command_MoveTo {
            get {
                return ResourceManager.GetString("Command_MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向上移动一行 的本地化字符串。
        /// </summary>
        internal static string Command_MoveUp {
            get {
                return ResourceManager.GetString("Command_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通视图模式 的本地化字符串。
        /// </summary>
        internal static string Command_NormalViewMode {
            get {
                return ResourceManager.GetString("Command_NormalViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字式列表 的本地化字符串。
        /// </summary>
        internal static string Command_NumberedList {
            get {
                return ResourceManager.GetString("Command_NumberedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开旧格式XML文件... 的本地化字符串。
        /// </summary>
        internal static string Command_OpenOldXMLFormat {
            get {
                return ResourceManager.GetString("Command_OpenOldXMLFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分页视图模式 的本地化字符串。
        /// </summary>
        internal static string Command_PageViewMode {
            get {
                return ResourceManager.GetString("Command_PageViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 段落格式 的本地化字符串。
        /// </summary>
        internal static string Command_ParagraphFormat {
            get {
                return ResourceManager.GetString("Command_ParagraphFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        internal static string Command_Paste {
            get {
                return ResourceManager.GetString("Command_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重做 的本地化字符串。
        /// </summary>
        internal static string Command_Redo {
            get {
                return ResourceManager.GetString("Command_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户注册... 的本地化字符串。
        /// </summary>
        internal static string Command_Register {
            get {
                return ResourceManager.GetString("Command_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存知识库... 的本地化字符串。
        /// </summary>
        internal static string Command_SaveKBLibrary {
            get {
                return ResourceManager.GetString("Command_SaveKBLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找和替换 的本地化字符串。
        /// </summary>
        internal static string Command_SearchReplace {
            get {
                return ResourceManager.GetString("Command_SearchReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string Command_SelectAll {
            get {
                return ResourceManager.GetString("Command_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文档默认样式 的本地化字符串。
        /// </summary>
        internal static string Command_SetDefaultStyle {
            get {
                return ResourceManager.GetString("Command_SetDefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带选择向下移动一行 的本地化字符串。
        /// </summary>
        internal static string Command_ShiftMoveDown {
            get {
                return ResourceManager.GetString("Command_ShiftMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带选择移动到行尾 的本地化字符串。
        /// </summary>
        internal static string Command_ShiftMoveEnd {
            get {
                return ResourceManager.GetString("Command_ShiftMoveEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带选择移动到行首 的本地化字符串。
        /// </summary>
        internal static string Command_ShiftMoveHome {
            get {
                return ResourceManager.GetString("Command_ShiftMoveHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带选择向左移动 的本地化字符串。
        /// </summary>
        internal static string Command_ShiftMoveLeft {
            get {
                return ResourceManager.GetString("Command_ShiftMoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带选择向下翻页 的本地化字符串。
        /// </summary>
        internal static string Command_ShiftMovePageDown {
            get {
                return ResourceManager.GetString("Command_ShiftMovePageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带选择向上翻页 的本地化字符串。
        /// </summary>
        internal static string Command_ShiftMovePageUp {
            get {
                return ResourceManager.GetString("Command_ShiftMovePageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带选择向右移动 的本地化字符串。
        /// </summary>
        internal static string Command_ShiftMoveRight {
            get {
                return ResourceManager.GetString("Command_ShiftMoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带选择向上移动一行 的本地化字符串。
        /// </summary>
        internal static string Command_ShiftMoveUp {
            get {
                return ResourceManager.GetString("Command_ShiftMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档签名 的本地化字符串。
        /// </summary>
        internal static string Command_SignDocument {
            get {
                return ResourceManager.GetString("Command_SignDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择性粘贴... 的本地化字符串。
        /// </summary>
        internal static string Command_SpecifyPaste {
            get {
                return ResourceManager.GetString("Command_SpecifyPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除线 的本地化字符串。
        /// </summary>
        internal static string Command_Strikeout {
            get {
                return ResourceManager.GetString("Command_Strikeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下标 的本地化字符串。
        /// </summary>
        internal static string Command_Subscript {
            get {
                return ResourceManager.GetString("Command_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上标 的本地化字符串。
        /// </summary>
        internal static string Command_Superscript {
            get {
                return ResourceManager.GetString("Command_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表格列 的本地化字符串。
        /// </summary>
        internal static string Command_Table_DeleteColumn {
            get {
                return ResourceManager.GetString("Command_Table_DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表格行 的本地化字符串。
        /// </summary>
        internal static string Command_Table_DeleteRow {
            get {
                return ResourceManager.GetString("Command_Table_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除表格 的本地化字符串。
        /// </summary>
        internal static string Command_Table_DeleteTable {
            get {
                return ResourceManager.GetString("Command_Table_DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在左侧插入表格列 的本地化字符串。
        /// </summary>
        internal static string Command_Table_InsertColumnLeft {
            get {
                return ResourceManager.GetString("Command_Table_InsertColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在右侧插入表格列 的本地化字符串。
        /// </summary>
        internal static string Command_Table_InsertColumnRight {
            get {
                return ResourceManager.GetString("Command_Table_InsertColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在下面插入表格行 的本地化字符串。
        /// </summary>
        internal static string Command_Table_InsertRowDown {
            get {
                return ResourceManager.GetString("Command_Table_InsertRowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在上面插入表格行 的本地化字符串。
        /// </summary>
        internal static string Command_Table_InsertRowUP {
            get {
                return ResourceManager.GetString("Command_Table_InsertRowUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入表格... 的本地化字符串。
        /// </summary>
        internal static string Command_Table_InsertTable {
            get {
                return ResourceManager.GetString("Command_Table_InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并单元格 的本地化字符串。
        /// </summary>
        internal static string Command_Table_MegeCell {
            get {
                return ResourceManager.GetString("Command_Table_MegeCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分单元格 的本地化字符串。
        /// </summary>
        internal static string Command_Table_SplitCell {
            get {
                return ResourceManager.GetString("Command_Table_SplitCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下划线 的本地化字符串。
        /// </summary>
        internal static string Command_Underline {
            get {
                return ResourceManager.GetString("Command_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        internal static string Command_Undo {
            get {
                return ResourceManager.GetString("Command_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据视图更新数据源 的本地化字符串。
        /// </summary>
        internal static string Command_UpdateDataSourceForView {
            get {
                return ResourceManager.GetString("Command_UpdateDataSourceForView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据数据源更新视图 的本地化字符串。
        /// </summary>
        internal static string Command_UpdateViewForDataSource {
            get {
                return ResourceManager.GetString("Command_UpdateViewForDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看XML源代码 的本地化字符串。
        /// </summary>
        internal static string Command_ViewXMLSource {
            get {
                return ResourceManager.GetString("Command_ViewXMLSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字数统计 的本地化字符串。
        /// </summary>
        internal static string Command_WordCount {
            get {
                return ResourceManager.GetString("Command_WordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} written by {1}. 的本地化字符串。
        /// </summary>
        internal static string CreatorTip_Name_Time {
            get {
                return ResourceManager.GetString("CreatorTip_Name_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string DeleteElement_Content {
            get {
                return ResourceManager.GetString("DeleteElement_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete{0} elements. 的本地化字符串。
        /// </summary>
        internal static string DeleteElements_Count {
            get {
                return ResourceManager.GetString("DeleteElements_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} deleted by {1}. 的本地化字符串。
        /// </summary>
        internal static string DeleterTip_Name_Time {
            get {
                return ResourceManager.GetString("DeleterTip_Name_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载“{0}”... 的本地化字符串。
        /// </summary>
        internal static string Downloading_URL {
            get {
                return ResourceManager.GetString("Downloading_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象“{0}”执行表达式“{1}”，结果为“{2}”。 的本地化字符串。
        /// </summary>
        internal static string ExecuteExpression_Sender_Expression_Result {
            get {
                return ResourceManager.GetString("ExecuteExpression_Sender_Expression_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象“{0}”执行表达式时未找到目标“{1}”,取消执行。 的本地化字符串。
        /// </summary>
        internal static string ExpressionMissTarget_Source_Target {
            get {
                return ResourceManager.GetString("ExpressionMissTarget_Source_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败。 的本地化字符串。
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载文件“{0}”失败，信息：{1} 的本地化字符串。
        /// </summary>
        internal static string FailToLoad_FileName_Message {
            get {
                return ResourceManager.GetString("FailToLoad_FileName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件“{0}”不存在。 的本地化字符串。
        /// </summary>
        internal static string FileNotExist_FileName {
            get {
                return ResourceManager.GetString("FileNotExist_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Footer 的本地化字符串。
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Header 的本地化字符串。
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image file(*.bmp,*.jpg,*.jpeg,*.gif,*.png)|*.bmp;*.jpg;*.jpeg;*.gif;*.png|All file|*.* 的本地化字符串。
        /// </summary>
        internal static string ImageFileFilter {
            get {
                return ResourceManager.GetString("ImageFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert“{0}” 的本地化字符串。
        /// </summary>
        internal static string InsertElement_Content {
            get {
                return ResourceManager.GetString("InsertElement_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert {0} elements 的本地化字符串。
        /// </summary>
        internal static string InsertElements_Count {
            get {
                return ResourceManager.GetString("InsertElements_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第{0}页 第{1}行 第{2}列。 的本地化字符串。
        /// </summary>
        internal static string LineInfo_PageIndex_LineIndex_ColumnIndex {
            get {
                return ResourceManager.GetString("LineInfo_PageIndex_LineIndex_ColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载完成，共加载了{0}。 的本地化字符串。
        /// </summary>
        internal static string LoadComplete_Size {
            get {
                return ResourceManager.GetString("LoadComplete_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载文件“{0}”... 的本地化字符串。
        /// </summary>
        internal static string Loading_FileName {
            get {
                return ResourceManager.GetString("Loading_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在以 {1} 格式加载文件“{0}”... 的本地化字符串。
        /// </summary>
        internal static string Loading_FileName_Format {
            get {
                return ResourceManager.GetString("Loading_FileName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经根据加密狗进行了软件注册了。 的本地化字符串。
        /// </summary>
        internal static string LoadLicenseFromDog {
            get {
                return ResourceManager.GetString("LoadLicenseFromDog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用“{0}”成功为“{1}”加载了{2}个列表项目。 的本地化字符串。
        /// </summary>
        internal static string LoadListItems_ProviderType_Name_Num {
            get {
                return ResourceManager.GetString("LoadListItems_ProviderType_Name_Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从缓存区加载列表项目，名称“{0}”，来源“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadListItemsFromBuffer_Name_URL {
            get {
                return ResourceManager.GetString("LoadListItemsFromBuffer_Name_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在使用“{0}”加载模板“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadTemplate_FS_FileName {
            get {
                return ResourceManager.GetString("LoadTemplate_FS_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miss property“{0}”. 的本地化字符串。
        /// </summary>
        internal static string MissProperty_Name {
            get {
                return ResourceManager.GetString("MissProperty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No document 的本地化字符串。
        /// </summary>
        internal static string NoDocument {
            get {
                return ResourceManager.GetString("NoDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No image 的本地化字符串。
        /// </summary>
        internal static string NoImage {
            get {
                return ResourceManager.GetString("NoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本软件没有在IE中运行的授权，请联系软件供应商获得相关授权。 的本地化字符串。
        /// </summary>
        internal static string NoLicenseToIEHost {
            get {
                return ResourceManager.GetString("NoLicenseToIEHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print completed. 的本地化字符串。
        /// </summary>
        internal static string PrintComplete {
            get {
                return ResourceManager.GetString("PrintComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Printing page {0} ... 的本地化字符串。
        /// </summary>
        internal static string PrintPage_PageIndex {
            get {
                return ResourceManager.GetString("PrintPage_PageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本软件已授权给“{0}”，请插入授权加密狗。若要加密狗请联系南京都昌信息科技有限公司。请不要破解盗版国产软件，支持民族产业。 的本地化字符串。
        /// </summary>
        internal static string PromptDevelopmentDog_Name {
            get {
                return ResourceManager.GetString("PromptDevelopmentDog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File &quot;{0}&quot; is readonly , can not save. 的本地化字符串。
        /// </summary>
        internal static string PromptReadonly_FileName {
            get {
                return ResourceManager.GetString("PromptReadonly_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请注册本软件，以更好的支持软件开发商。 的本地化字符串。
        /// </summary>
        internal static string PromptRegister {
            get {
                return ResourceManager.GetString("PromptRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace {0} times. 的本地化字符串。
        /// </summary>
        internal static string PromptReplaceAllResult_Times {
            get {
                return ResourceManager.GetString("PromptReplaceAllResult_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File &quot;{0}&quot; modified , save it ? 的本地化字符串。
        /// </summary>
        internal static string PromptSaveFile_Name {
            get {
                return ResourceManager.GetString("PromptSaveFile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property“{0}”Can not has parameter. 的本地化字符串。
        /// </summary>
        internal static string PropertyCannotHasParameter_Name {
            get {
                return ResourceManager.GetString("PropertyCannotHasParameter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property“{0}”is readonly. 的本地化字符串。
        /// </summary>
        internal static string PropertyIsReadonly_Name {
            get {
                return ResourceManager.GetString("PropertyIsReadonly_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File modified ,save it? 的本地化字符串。
        /// </summary>
        internal static string QuerySave {
            get {
                return ResourceManager.GetString("QuerySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Readonly 的本地化字符串。
        /// </summary>
        internal static string Readonly {
            get {
                return ResourceManager.GetString("Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register fail! 的本地化字符串。
        /// </summary>
        internal static string RegiserFail {
            get {
                return ResourceManager.GetString("RegiserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register success. 的本地化字符串。
        /// </summary>
        internal static string RegisterOK {
            get {
                return ResourceManager.GetString("RegisterOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本软件已注册，授权给“{0}”。 的本地化字符串。
        /// </summary>
        internal static string RegisterTitle_UserName {
            get {
                return ResourceManager.GetString("RegisterTitle_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存完成，共保存了{0}。 的本地化字符串。
        /// </summary>
        internal static string SaveComplete_Size {
            get {
                return ResourceManager.GetString("SaveComplete_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存文件“{0}”... 的本地化字符串。
        /// </summary>
        internal static string Saving_FileName {
            get {
                return ResourceManager.GetString("Saving_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to compile script. 的本地化字符串。
        /// </summary>
        internal static string ScriptCompileFail {
            get {
                return ResourceManager.GetString("ScriptCompileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success to compile script. 的本地化字符串。
        /// </summary>
        internal static string ScriptCompileOK {
            get {
                return ResourceManager.GetString("ScriptCompileOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML file , RTF file|*.xml;*.rtf|All file|*.* 的本地化字符串。
        /// </summary>
        internal static string StdOpenFileFilter {
            get {
                return ResourceManager.GetString("StdOpenFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML,RTF,HTML,TXT file|*.xml;*.rtf;*.htm;*.html;*.txt|All file|*.* 的本地化字符串。
        /// </summary>
        internal static string StdSaveFileFilter {
            get {
                return ResourceManager.GetString("StdSaveFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System alert 的本地化字符串。
        /// </summary>
        internal static string SystemAlert {
            get {
                return ResourceManager.GetString("SystemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System alert 的本地化字符串。
        /// </summary>
        internal static string TipTitle {
            get {
                return ResourceManager.GetString("TipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XDesigner.Writer[Unregister] [%pageindex%] of [%pagecount%] 的本地化字符串。
        /// </summary>
        internal static string UnRegisterPageTitle {
            get {
                return ResourceManager.GetString("UnRegisterPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本软件未注册。 的本地化字符串。
        /// </summary>
        internal static string UnRegisterTitle {
            get {
                return ResourceManager.GetString("UnRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象“{0}”内容为“{1}”，数据校验错误“{2}”。 的本地化字符串。
        /// </summary>
        internal static string ValueInvalidate_Source_Value_Result {
            get {
                return ResourceManager.GetString("ValueInvalidate_Source_Value_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value validate fail. 的本地化字符串。
        /// </summary>
        internal static string ValueValidateFail {
            get {
                return ResourceManager.GetString("ValueValidateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value validate success. 的本地化字符串。
        /// </summary>
        internal static string ValueValidateOK {
            get {
                return ResourceManager.GetString("ValueValidateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制到何处？ 的本地化字符串。
        /// </summary>
        internal static string WhereToCopy {
            get {
                return ResourceManager.GetString("WhereToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到何处？ 的本地化字符串。
        /// </summary>
        internal static string WhereToMove {
            get {
                return ResourceManager.GetString("WhereToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML文件|*.xml 的本地化字符串。
        /// </summary>
        internal static string XMLFilter {
            get {
                return ResourceManager.GetString("XMLFilter", resourceCulture);
            }
        }
    }
}
