/*****************************
CSharpWriter is a RTF style Text writer control written by C#2.0,Currently,
it use <LGPL> license(maybe change later).More than RichTextBox, 
It is provide a DOM to access every thing in document and save in XML format.
It can use in WinForm.NET ,WPF,Console application.Any idea about CSharpWriter 
can send to 28348092@qq.com(or yyf9989@hotmail.com).
*****************************///@DCHC@
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSoft.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCSoft.Data.DataStrings", typeof(DataStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 对象已经关闭了。 的本地化字符串。
        /// </summary>
        internal static string AlertClosed {
            get {
                return ResourceManager.GetString("AlertClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入服务器地址和用户登录名。 的本地化字符串。
        /// </summary>
        internal static string AlertInputServerAndUser {
            get {
                return ResourceManager.GetString("AlertInputServerAndUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个合适的属性，该属性必须是公开的可读写的，最好是返回一个列表。 的本地化字符串。
        /// </summary>
        internal static string AlertSelectPropertyMember {
            get {
                return ResourceManager.GetString("AlertSelectPropertyMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能从运行中的.NET程序集中获得数据。 的本地化字符串。
        /// </summary>
        internal static string AssemblyConnectionDescription {
            get {
                return ResourceManager.GetString("AssemblyConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .NET程序集文件(*.dll,*.exe)|*.dll;*.exe 的本地化字符串。
        /// </summary>
        internal static string AssemblyFilter {
            get {
                return ResourceManager.GetString("AssemblyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是合法的 DBF（dBase III）文件格式 的本地化字符串。
        /// </summary>
        internal static string BadDBFFormat {
            get {
                return ResourceManager.GetString("BadDBFFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数“{0}”的数据类型错误，需要的类型为“{1}”，实际数值为“{2}”。 的本地化字符串。
        /// </summary>
        internal static string BadParameterValueType_Name_Type_Value {
            get {
                return ResourceManager.GetString("BadParameterValueType_Name_Type_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能对一个数据读取器定义多个索引字段。 的本地化字符串。
        /// </summary>
        internal static string CanNotDefineMultiIndexInOneReader {
            get {
                return ResourceManager.GetString("CanNotDefineMultiIndexInOneReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能定义多个主索引字段。 的本地化字符串。
        /// </summary>
        internal static string CanNotDefineMultiMainIndexField {
            get {
                return ResourceManager.GetString("CanNotDefineMultiMainIndexField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭数据库连接“{1}”。 的本地化字符串。
        /// </summary>
        internal static string CloseConnection_String {
            get {
                return ResourceManager.GetString("CloseConnection_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接已经关闭了。 的本地化字符串。
        /// </summary>
        internal static string ConnectionClosed {
            get {
                return ResourceManager.GetString("ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能从CSV格式的数据文件中获得数据。 的本地化字符串。
        /// </summary>
        internal static string CSVConnectionDescription {
            get {
                return ResourceManager.GetString("CSVConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSV数据文件(*.csv)|*.csv 的本地化字符串。
        /// </summary>
        internal static string CSVFilter {
            get {
                return ResourceManager.GetString("CSVFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库结构 的本地化字符串。
        /// </summary>
        internal static string DataBaseSchema {
            get {
                return ResourceManager.GetString("DataBaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能从Dbase III 格式的数据文件中获得数据。 的本地化字符串。
        /// </summary>
        internal static string DBaseConnectionDescription {
            get {
                return ResourceManager.GetString("DBaseConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBF数据文件(*.dbf)|*.dbf 的本地化字符串。
        /// </summary>
        internal static string DBFFilter {
            get {
                return ResourceManager.GetString("DBFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录 的本地化字符串。
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能从Windows系统的日志记录中获得数据。 的本地化字符串。
        /// </summary>
        internal static string EventLogConnectionDescription {
            get {
                return ResourceManager.GetString("EventLogConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能从Excel二进制文件中获得数据。 的本地化字符串。
        /// </summary>
        internal static string ExcelBinaryConnectionDescription {
            get {
                return ResourceManager.GetString("ExcelBinaryConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能找到文件“{0}”。 的本地化字符串。
        /// </summary>
        internal static string FileNotFound_FileName {
            get {
                return ResourceManager.GetString("FileNotFound_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能从操作系统文件目录系统中获得数据。 的本地化字符串。
        /// </summary>
        internal static string FileSystemConnectionDescription {
            get {
                return ResourceManager.GetString("FileSystemConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes,No|True,False|是,否|真,假|好,差|男,女|是,|,否 的本地化字符串。
        /// </summary>
        internal static string FormatSample_Boolean {
            get {
                return ResourceManager.GetString("FormatSample_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 00.00|大写中文|小写中文|#.00|c 的本地化字符串。
        /// </summary>
        internal static string FormatSample_Currency {
            get {
                return ResourceManager.GetString("FormatSample_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-MM-dd HH:mm:ss|yyyy-MM-dd|yyyy-MM-dd hh:mm:ss|HH:mm:ss|yyyy年MM月dd日|yyyy年MM月dd日 HH时mm分ss秒|d|D|f|F 的本地化字符串。
        /// </summary>
        internal static string FormatSample_DateTime {
            get {
                return ResourceManager.GetString("FormatSample_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共显示{0}行{1}列数据。 的本地化字符串。
        /// </summary>
        internal static string GridDataInfo_Rows_Cols {
            get {
                return ResourceManager.GetString("GridDataInfo_Rows_Cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从文件“{0}”加载数据集XML文档时发生错误“{1}”。 的本地化字符串。
        /// </summary>
        internal static string LoadDataSetXMLError_File_Message {
            get {
                return ResourceManager.GetString("LoadDataSetXMLError_File_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载... 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型“{0}”缺少成员“{1}”。 的本地化字符串。
        /// </summary>
        internal static string MissMember_Type_Member {
            get {
                return ResourceManager.GetString("MissMember_Type_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能从 MySQL 数据库中访问数据。 的本地化字符串。
        /// </summary>
        internal static string MySQLConnectionDescription {
            get {
                return ResourceManager.GetString("MySQLConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有当前记录 的本地化字符串。
        /// </summary>
        internal static string NoCurrentRecord {
            get {
                return ResourceManager.GetString("NoCurrentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据 的本地化字符串。
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有任何数据。 的本地化字符串。
        /// </summary>
        internal static string NoneData {
            get {
                return ResourceManager.GetString("NoneData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未指定文件名。 的本地化字符串。
        /// </summary>
        internal static string NotSpecifyFileName {
            get {
                return ResourceManager.GetString("NotSpecifyFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开数据库连接“{0}”。 的本地化字符串。
        /// </summary>
        internal static string OpenConnection_String {
            get {
                return ResourceManager.GetString("OpenConnection_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从文件“{1}”读取了{0}数据。 的本地化字符串。
        /// </summary>
        internal static string ReadBytes_Bytes_Name {
            get {
                return ResourceManager.GetString("ReadBytes_Bytes_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用“{0}”编码格式从文件“{1}”中读取{2}个字符。 的本地化字符串。
        /// </summary>
        internal static string ReadChars_Encoding_Name_Length {
            get {
                return ResourceManager.GetString("ReadChars_Encoding_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据读取器已经关闭了 的本地化字符串。
        /// </summary>
        internal static string ReaderClosed {
            get {
                return ResourceManager.GetString("ReaderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据读取完毕。 的本地化字符串。
        /// </summary>
        internal static string ReaderEOF {
            get {
                return ResourceManager.GetString("ReaderEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能从对象“{0}”获得任何数据。 的本地化字符串。
        /// </summary>
        internal static string ReturnNothing_MemberName {
            get {
                return ResourceManager.GetString("ReturnNothing_MemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   中文ABC   的本地化字符串。
        /// </summary>
        internal static string SampleText {
            get {
                return ResourceManager.GetString("SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存数据集XML文件到“{0}”时发生错误“{1}”。 的本地化字符串。
        /// </summary>
        internal static string SaveDataSetXMLError_File_Message {
            get {
                return ResourceManager.GetString("SaveDataSetXMLError_File_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统消息 的本地化字符串。
        /// </summary>
        internal static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共计{0}行，{1}列。 的本地化字符串。
        /// </summary>
        internal static string Total_Rows_Cols {
            get {
                return ResourceManager.GetString("Total_Rows_Cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [共{0}张表，{1}个字段] 的本地化字符串。
        /// </summary>
        internal static string Total_Tables_Fields {
            get {
                return ResourceManager.GetString("Total_Tables_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能从WMI(Windows系统管理)中获得数据。 的本地化字符串。
        /// </summary>
        internal static string WMIConnectionDescription {
            get {
                return ResourceManager.GetString("WMIConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel数据文件(*.xls)|*.xls 的本地化字符串。
        /// </summary>
        internal static string XLSFilter {
            get {
                return ResourceManager.GetString("XLSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能从XML文件中获得数据。 的本地化字符串。
        /// </summary>
        internal static string XMLConnectionDescription {
            get {
                return ResourceManager.GetString("XMLConnectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XML文件(*.xml)|*.xml 的本地化字符串。
        /// </summary>
        internal static string XMLFilter {
            get {
                return ResourceManager.GetString("XMLFilter", resourceCulture);
            }
        }
    }
}
